version: '3.4'

services:
  docker:
    image: docker
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    #command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app\Laufzeitumgebung:app --host 0.0.0.0 --port 7000"]
    expose:
      - 1883
      - 1884
      - 7000

    ports:
      - 1883:1883
      - 1884:1884
      - 7000:7000


